import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "./context/ThemeProvider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import DashboardSidebar from "./components/sidebar";
import { Toaster } from "sonner";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    suppressHydrationWarning>
      <body className="min-h-full flex flex-col">
        
        <SidebarProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
                <div>
                  <DashboardSidebar />
                  <div className="bg-background text-sidebar-foreground min-h-screen pt-1.5 pl-1">
                    <SidebarTrigger />
                  </div>
                </div>
                <main className="min-w-full dark:bg-background dark:text-sidebar-foreground p-2">
                  {children}
                </main>
            </ThemeProvider>
          </SidebarProvider>
          <Toaster position="top-center"/>
      </body>
    </html>
  );
}
